### ISSUE TITLE
Error message not sent to the Concourse client.

### ISSUE THREAD

**Issue by jonathanmarvens** [cinchapi/concourse#236]
I experienced an error while attempting to use the JSON importer:
```
~/Code/github.com/cinchapi/concourse git$develop(09eac17)
❯ concourse import -d $HOME/Downloads/datasets/airbnb/airbnb_session_data.json -t json
password for [admin]: *****
Starting import...
ERROR: org.apache.thrift.TApplicationException: Internal error processing insertJson
```

`ERROR: org.apache.thrift.TApplicationException: Internal error processing insertJson` is all that the client provided me with, but when I check `/var/log/concourse/error.log`, I see:
```
2016-09-26 16:33:31,323 [Client Worker 10] ERROR - Internal error processing insertJson
com.cinchapi.concourse.thrift.InvalidArgumentException: Cannot use a blank value
	at com.cinchapi.concourse.server.ConcourseServer$ThriftExceptionHandler.invoke(ConcourseServer.java:4333) ~[concourse-server-0.5.0.6-SNAPSHOT.jar:0.5.0.6-SNAPSHOT]
	at com.cinchapi.concourse.thrift.ConcourseService$Processor$insertJson.getResult(ConcourseService.java:16881) ~[concourse-driver-java-0.5.0.6-SNAPSHOT.jar:0.5.0.6-SNAPSHOT]
	at com.cinchapi.concourse.thrift.ConcourseService$Processor$insertJson.getResult(ConcourseService.java:16865) ~[concourse-driver-java-0.5.0.6-SNAPSHOT.jar:0.5.0.6-SNAPSHOT]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [libthrift-0.9.3.jar:0.9.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

```

The rest of the error message (`com.cinchapi.concourse.thrift.InvalidArgumentException: Cannot use a blank value`) should also be sent to the client.

__CC:__ @jtnelson.

**Comment by dubex** [comment]
@jonathanmarvens Could you please help me to reproduce the issue?
