### ISSUE TITLE
Docker: Java heap space

### ISSUE THREAD

**Issue by mehrdd** [cinchapi/concourse#358]
Hi,
I'm trying to install Concourse via Docker.
But i'm getting this error in console after install:

> Exception in thread "Client Worker 0" java.lang.OutOfMemoryError: Java heap space
	at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:379)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:230)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:27)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/1578360/52949688-3f321780-3392-11e9-9371-cbc6d2b7e500.png)

**Comment by jtnelson** [comment]
Hi @mehrdd,

Thanks for reporting this issue. What command are you using to run Concourse via Docker?  After the container starts, are you running any additional commands?

Thanks in advance for the info. We'll get you up and running soon once we're able to diagnose things further.

Best,
Jeff

**Comment by mehrdd** [comment]
Hi Jeff,
I'm just using normal commands like:
```
docker run -p 1717:1717 --name concourse cinchapi/concourse
```
After installing my Concourse container, i opened my browser and entered http://localhost:1717 

I'm trying to use Concourse with node.js for a very dynamic-query-based SaaS project like [Zoho Creator](https://www.zoho.com/creator/)
Is Concourse a good fit for such project? 

Thank you Jeff,

Best regards,
Mehrdad
